project_id = "ahs1"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = false

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.audio-music]
public = false
file_size_limit = "50MiB"

[storage.buckets.audio-jingles]
public = false
file_size_limit = "20MiB"

[storage.buckets.audio-advertisements]
public = false
file_size_limit = "20MiB"

[storage.buckets.audio-temporary]
public = false
file_size_limit = "50MiB"
