// Base de connaissances AHS1 (41 entrées) fournie par l'exploitant — transcrite
// telle quelle depuis AHS1_AI_Knowledge_Base_V1.md. Utilisée en mode "règles"
// (pas de LLM, cf. player-faq.ts) : chaque entrée porte ses propres variantes
// de formulation et mots-clés pour le matching, sa priorité, et si elle doit
// forcer une escalade vers le support humain plutôt que clore la conversation.

export interface FaqEntry {
  id: string;
  category: string;
  intent: string;
  priority: "normal" | "high" | "critical";
  variants: string[];
  keywords: string[];
  answer: string;
  escalate: boolean;
}

export const FAQ_ENTRIES: FaqEntry[] = [
  {
    id: "AHS1-FAQ-001",
    category: "Général",
    intent: "general",
    priority: "normal",
    variants: ["AHS1 c'est quoi", "À quoi sert AHS1", "C'est quoi Audio Hub Stream"],
    keywords: ["AHS1", "Audio Hub Stream", "diffusion audio"],
    answer:
      "AHS1 (Audio Hub Stream) est une solution de diffusion audio destinée aux commerces et établissements professionnels. Elle permet d'automatiser la diffusion de musiques, jingles et messages programmés depuis une interface de gestion.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-002",
    category: "Général",
    intent: "general",
    priority: "normal",
    variants: ["Pour quel type de commerce", "Qui peut utiliser AHS1", "AHS1 pour magasin"],
    keywords: ["magasin", "commerce", "restaurant", "hôtel"],
    answer:
      "AHS1 est conçu pour les magasins, commerces, restaurants, hôtels, salles d'attente et autres établissements ayant besoin d'une diffusion audio automatisée.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-003",
    category: "Général",
    intent: "automation",
    priority: "normal",
    variants: ["AHS1 fonctionne tout seul", "Faut-il lancer la musique", "Lecture automatique"],
    keywords: ["automatique", "autodj", "démarrage"],
    answer: "Oui. Après configuration, AHS1 est conçu pour démarrer et diffuser automatiquement les contenus prévus par la programmation.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-004",
    category: "Général",
    intent: "hardware",
    priority: "normal",
    variants: ["Faut-il un PC", "Est-ce qu'un ordinateur est obligatoire"],
    keywords: ["ordinateur", "PC", "appareil"],
    answer: "Non. AHS1 est prévu pour fonctionner sur un appareil de diffusion dédié. La gestion peut être effectuée à distance depuis une interface compatible.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-005",
    category: "Général",
    intent: "remote_management",
    priority: "normal",
    variants: ["Gérer depuis smartphone", "Application téléphone", "Contrôler AHS1 avec mobile"],
    keywords: ["smartphone", "téléphone", "mobile"],
    answer: "Oui. L'architecture AHS1 prévoit une gestion à distance depuis un téléphone, une tablette ou un ordinateur compatible.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-006",
    category: "Diffusion",
    intent: "playback",
    priority: "normal",
    variants: ["Comment AHS1 diffuse la musique", "Comment marche la lecture"],
    keywords: ["lecture", "diffusion", "programmation"],
    answer: "AHS1 lit automatiquement les contenus audio disponibles selon la programmation configurée pour l'établissement.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-007",
    category: "Diffusion",
    intent: "playlist",
    priority: "normal",
    variants: ["Plusieurs playlists", "Créer des listes musicales", "Différentes playlists"],
    keywords: ["playlist", "listes", "musique"],
    answer: "Oui. AHS1 est conçu pour organiser les contenus en playlists afin d'adapter la diffusion aux différents moments ou usages.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-008",
    category: "Diffusion",
    intent: "schedule",
    priority: "normal",
    variants: ["Playlist matin soir", "Changer de musique selon l'heure", "Programmation horaire"],
    keywords: ["planning", "horaire", "playlist"],
    answer: "Oui. La programmation peut associer différentes playlists à des horaires définis.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-009",
    category: "Diffusion",
    intent: "continuous_playback",
    priority: "normal",
    variants: ["Musique 24h", "Lecture continue", "Diffusion sans interruption"],
    keywords: ["continu", "24h", "lecture"],
    answer: "Oui. AHS1 est conçu pour assurer une diffusion continue pendant les périodes de fonctionnement configurées.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-010",
    category: "Publicité",
    intent: "advertising",
    priority: "normal",
    variants: ["Faire passer des pubs", "Publicité magasin", "Messages publicitaires"],
    keywords: ["publicité", "pub", "annonce"],
    answer: "Oui. Les fichiers publicitaires peuvent être intégrés à la programmation audio.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-011",
    category: "Publicité",
    intent: "advertising_schedule",
    priority: "normal",
    variants: ["Pub à 10h", "Annonce programmée", "Publicité horaire"],
    keywords: ["publicité", "horaire", "campagne"],
    answer: "Oui, lorsqu'une programmation horaire est configurée pour ce contenu.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-012",
    category: "Publicité",
    intent: "jingle",
    priority: "normal",
    variants: ["Jingles magasin", "Insérer un jingle", "Jingle radio"],
    keywords: ["jingle", "habillage", "audio"],
    answer: "Oui. Les jingles peuvent être ajoutés aux contenus utilisés par la programmation.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-013",
    category: "Publicité",
    intent: "remote_content",
    priority: "normal",
    variants: ["Changer une pub à distance", "Remplacer une annonce"],
    keywords: ["publicité", "distance", "synchronisation"],
    answer: "Oui, l'objectif d'AHS1 est de permettre la gestion à distance des contenus et de leur programmation lorsque l'appareil est synchronisé.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-014",
    category: "Réseau",
    intent: "network",
    priority: "normal",
    variants: ["Internet obligatoire", "Connexion Internet", "AHS1 sans Internet"],
    keywords: ["internet", "réseau", "connexion", "wifi"],
    answer:
      "Une connexion Internet est nécessaire pour les fonctions de synchronisation et de gestion à distance. La diffusion peut également utiliser les contenus stockés localement selon la configuration.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-015",
    category: "Réseau",
    intent: "offline_playback",
    priority: "normal",
    variants: ["Coupure Internet", "Plus de Wi-Fi", "Internet en panne"],
    keywords: ["coupure", "internet", "cache", "local", "wifi"],
    answer: "AHS1 est conçu pour pouvoir continuer la diffusion à partir des contenus disponibles localement, lorsque ceux-ci ont été synchronisés sur l'appareil.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-016",
    category: "Réseau",
    intent: "offline_playback",
    priority: "normal",
    variants: ["Musique pendant coupure réseau", "Ça coupe sans Internet"],
    keywords: ["offline", "lecture locale", "réseau"],
    answer: "Pas nécessairement. Si les contenus nécessaires sont disponibles localement, AHS1 peut continuer la diffusion pendant la coupure réseau.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-017",
    category: "Réseau",
    intent: "sync",
    priority: "normal",
    variants: ["Retour Internet", "Resynchronisation", "Après une coupure réseau"],
    keywords: ["synchronisation", "réseau", "retour"],
    answer: "Lorsque la connexion revient, AHS1 peut reprendre la synchronisation avec le serveur afin de récupérer les modifications et nouveaux contenus disponibles.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-018",
    category: "Stockage",
    intent: "storage",
    priority: "normal",
    variants: ["Pourquoi stocker les musiques", "Cache local"],
    keywords: ["stockage", "cache", "local"],
    answer: "Le stockage local permet de conserver les contenus nécessaires à la diffusion et d'améliorer la continuité de service en cas de coupure réseau.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-019",
    category: "Stockage",
    intent: "storage_capacity",
    priority: "normal",
    variants: ["Capacité musique", "Combien de chansons", "Stockage audio"],
    keywords: ["stockage", "capacité", "MP3", "WAV"],
    answer: "La quantité de musique dépend de la capacité de stockage disponible et du format audio utilisé. Les fichiers WAV occupent beaucoup plus d'espace que les MP3.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-020",
    category: "Stockage",
    intent: "storage_full",
    priority: "high",
    variants: ["Disque plein", "Plus de place", "Stockage saturé"],
    keywords: ["stockage", "disque plein", "espace"],
    answer:
      "Le système doit surveiller l'espace disponible et signaler une capacité insuffisante. Les règles de conservation et de synchronisation doivent empêcher une saturation non contrôlée.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-021",
    category: "Audio",
    intent: "audio_format",
    priority: "normal",
    variants: ["Formats supportés", "MP3 ou WAV", "Format musique"],
    keywords: ["format", "MP3", "WAV", "audio"],
    answer: "Les formats officiellement pris en charge doivent être définis par la configuration technique d'AHS1. Le MP3 est adapté à la diffusion et permet de limiter l'espace utilisé.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-022",
    category: "Audio",
    intent: "audio_format",
    priority: "normal",
    variants: ["MP3 compatible", "Musique MP3"],
    keywords: ["MP3", "audio"],
    answer: "Oui. Le MP3 est adapté à la diffusion audio sur AHS1 et offre un bon compromis entre qualité et stockage.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-023",
    category: "Audio",
    intent: "audio_format",
    priority: "normal",
    variants: ["Fichier WAV", "WAV sur AHS1"],
    keywords: ["WAV", "audio", "stockage"],
    answer: "Le WAV peut être utilisé si la configuration technique d'AHS1 le prend en charge. Il nécessite davantage de stockage qu'un MP3 équivalent.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-024",
    category: "Audio",
    intent: "audio_quality",
    priority: "normal",
    variants: ["Quel bitrate", "320 kbps", "Qualité MP3"],
    keywords: ["qualité", "bitrate", "MP3"],
    answer:
      "Pour une diffusion en magasin, un MP3 de bonne qualité constitue généralement un bon compromis entre qualité audio et espace de stockage. La qualité exacte doit être définie selon les besoins du projet.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-025",
    category: "Appareil",
    intent: "hardware",
    priority: "normal",
    variants: ["Boîtier avec écran", "Écran obligatoire"],
    keywords: ["écran", "boîtier", "appareil"],
    answer: "Non. Le concept AHS1 prévoit un appareil de diffusion pouvant fonctionner sans écran permanent, avec une gestion à distance.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-026",
    category: "Appareil",
    intent: "autostart",
    priority: "normal",
    variants: ["Auto boot", "Démarrage automatique", "Lecture au démarrage"],
    keywords: ["boot", "démarrage", "automatique"],
    answer: "Oui, l'architecture AHS1 prévoit un démarrage automatique du service de diffusion après le démarrage de l'appareil.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-027",
    category: "Appareil",
    intent: "power_recovery",
    priority: "normal",
    variants: ["Panne électrique", "Redémarrage après coupure"],
    keywords: ["courant", "redémarrage", "alimentation"],
    answer: "Après le retour de l'alimentation, AHS1 doit pouvoir redémarrer automatiquement et reprendre son fonctionnement selon sa configuration.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-028",
    category: "Gestion",
    intent: "remote_schedule",
    priority: "normal",
    variants: ["Changer planning à distance", "Modifier playlist depuis téléphone"],
    keywords: ["programmation", "distance", "synchronisation"],
    answer: "Oui. Les modifications de programmation peuvent être synchronisées avec l'appareil lorsqu'il est connecté.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-029",
    category: "Gestion",
    intent: "device_status",
    priority: "normal",
    variants: ["Statut appareil", "AHS1 en ligne", "Voir connexion"],
    keywords: ["statut", "online", "offline"],
    answer: "L'interface AHS1 peut afficher l'état de connexion de l'appareil afin de faciliter le suivi et le dépannage.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-030",
    category: "Gestion",
    intent: "multi_site",
    priority: "normal",
    variants: ["Multi magasins", "Plusieurs AHS1", "Gérer plusieurs boutiques"],
    keywords: ["multi-site", "magasins", "appareils"],
    answer:
      "L'architecture AHS1 peut être conçue pour gérer plusieurs appareils et établissements depuis une même interface. La disponibilité exacte de cette fonction dépend de la version déployée.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-031",
    category: "Compte",
    intent: "users",
    priority: "normal",
    variants: ["Plusieurs comptes", "Employés", "Accès équipe"],
    keywords: ["utilisateurs", "comptes", "équipe"],
    answer: "Oui, l'architecture peut prévoir plusieurs utilisateurs avec des niveaux de permissions différents.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-032",
    category: "Compte",
    intent: "permissions",
    priority: "normal",
    variants: ["Droits employés", "Permissions", "Compte limité"],
    keywords: ["permissions", "rôles", "employés"],
    answer: "Oui, un système de rôles et permissions peut limiter les fonctions accessibles à chaque utilisateur.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-033",
    category: "Dépannage",
    intent: "no_audio",
    priority: "high",
    variants: ["Plus de musique", "Aucun son", "Le son ne marche plus"],
    keywords: ["son", "volume", "sortie audio"],
    answer: "Vérifiez d'abord le volume, les branchements audio et la sortie audio sélectionnée. Vérifiez ensuite l'état de l'appareil et la lecture depuis l'interface AHS1.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-034",
    category: "Dépannage",
    intent: "playback_stuck",
    priority: "high",
    variants: ["Une seule musique tourne", "Playlist bloquée", "Musique bloquée"],
    keywords: ["playlist", "blocage", "lecture"],
    answer: "Vérifiez que la playlist est active, que la programmation est correcte et que l'appareil dispose bien de contenus lisibles. Vérifiez également son état de connexion.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-035",
    category: "Dépannage",
    intent: "device_offline",
    priority: "high",
    variants: ["AHS1 offline", "Appareil déconnecté", "Boîtier hors connexion"],
    keywords: ["offline", "réseau", "alimentation", "wifi"],
    answer: "Vérifiez l'alimentation puis la connexion réseau. Si l'appareil est toujours hors ligne après ces vérifications, redémarrez-le et contrôlez son statut dans l'interface.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-036",
    category: "Dépannage",
    intent: "content_not_playing",
    priority: "high",
    variants: ["Pub non diffusée", "Annonce absente", "Jingle non joué"],
    keywords: ["publicité", "programmation", "fichier"],
    answer: "Vérifiez que le fichier est présent, lisible, correctement programmé et que l'appareil a bien synchronisé la dernière configuration.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-037",
    category: "Dépannage",
    intent: "audio_dropout",
    priority: "high",
    variants: ["Coupures audio", "Son qui saute", "Lecture saccadée"],
    keywords: ["coupure", "saccade", "audio"],
    answer:
      "Vérifiez la connexion réseau si la source dépend du réseau, le stockage local, le fichier audio et la sortie audio. Si les contenus sont disponibles localement, la lecture locale peut permettre de continuer malgré une coupure Internet.",
    escalate: false,
  },
  {
    id: "AHS1-FAQ-038",
    category: "Support",
    intent: "unknown_issue",
    priority: "high",
    variants: ["Besoin d'aide", "Problème non résolu", "Support AHS1"],
    keywords: ["support", "problème", "assistance"],
    answer:
      "Je n'ai pas suffisamment d'informations dans ma base de connaissances pour répondre précisément. Décris le problème, le modèle de l'appareil, son état de connexion et ce qui s'est passé juste avant la panne.",
    escalate: true,
  },
  {
    id: "AHS1-FAQ-039",
    category: "Sécurité",
    intent: "security",
    priority: "normal",
    variants: ["Sécurité connexion", "Connexion sécurisée"],
    keywords: ["sécurité", "HTTPS", "authentification"],
    answer:
      "AHS1 doit utiliser des communications sécurisées entre l'interface de gestion, les services et les appareils. Les détails exacts dépendent de l'architecture et de la version déployée.",
    escalate: false,
  },
];
